#!/usr/bin/env node

'use strict';

var fs = require('fs');

module.exports.validateCommitMessage = function (message) {
  var errorCode = 0,
    lines = message.split('\n'),
    line = lines.shift();

  if (line && line.length > 50) {
    console.error('Commit message title has more than 50 characters');
    errorCode = 1;
  }

  line = lines.shift();
  if (line && line.length > 0) {
    console.error('Second commit message line is not empty');
    errorCode = 1;
  }

  lines.forEach(function (line) {
    if (line && line.charAt(0) !== '#' && line.length > 72) {
      console.error('Commit message body line has more than 72 characters');
      errorCode = 1;
    }
  });

  return errorCode;
};

fs.readFile(process.argv[2], function(err, buffer) {
  process.exit(module.exports.validateCommitMessage(buffer.toString()));
});
