#!/usr/bin/env bash

# Based on: https://github.com/henrik/dotfiles/blob/master/git_template/hooks/pre-commit

data=$(cat)
exitcodes=()
hookname=`basename $0`

# Run each hook, passing through STDIN and storing the exit code.
# We don't want to bail at the first failure, as the user might
# then bypass the hooks without knowing about additional issues.
for hook in $GIT_DIR/hooks/$hookname.*; do
    test -x "$hook" || continue
    echo "$data" | "$hook"
    exitcodes+=($?)
done

# If any exit code isn't 0, bail.
for i in "${exitcodes[@]}"; do
    if [ "$i" != 0 ]; then
        tput setaf 1
        echo "-- COMMIT REJECTED --"
        exit $i
    fi
done
