#!/usr/bin/env node

'use strict';

let exitCode = 0,
    commitHooks = [
        './pre-commit.d/corefiles',
        './pre-commit.d/debugcode',
        './pre-commit.d/codestyle',
    ];

commitHooks.forEach((hook) => {
    exitCode = exitCode || require(hook).run();
});

if (exitCode) {
    console.log('-- Pre-commit hook failed --');
}

process.exit(exitCode);
