#!/usr/bin/env node

'use strict';

var exitCode = 0,
    commitHooks = [
        './pre-commit.d/corefiles',
        './pre-commit.d/debugcode',
    ];

commitHooks.forEach(function (hook) {
    exitCode = exitCode || require(hook).run();
});

if (exitCode) {
    console.log('-- Pre-commit hook failed --');
}

process.exit(exitCode);
