#!/usr/bin/env node

'use strict';

let exec = require('child_process').execSync;
let fs = require('fs');
let path = require('path');

module.exports.getPhpFiles = (files) => {
    return files.filter((file) => {
        return -1 !== ['.php', '.phtml'].indexOf(path.extname(file));
    });
};

module.exports.skipDeletedFiles = (files) => {
    return files.filter((file) => {
        return fs.existsSync(file);
    });
};

module.exports.run = () => {
    let files = exec('git diff-index --name-only HEAD').toString().trim().split('\n');

    try {
        let phpFiles = module.exports.skipDeletedFiles(module.exports.getPhpFiles(files));


        if (phpFiles.length) {
            exec('phpcs --encoding=utf-8 ' + phpFiles.join(' '), { stdio: [0, 1, 2] });
        }

        return 0;
    } catch (e) {
        return 1;
    }
};
