#!/usr/bin/env node

'use strict';

var exec = require('child_process').execSync;

module.exports.isCoreFileEdited = function (files) {
    var exitCode = 0,
        coreFilesPatterns = [
            'app/code/core',
            'app/Mage.php$',
            '^index.php$',
            'lib/(Zend|Mage|Varien)',
            'app/design/(adminhtml|frontend)/(base|default)',
            'skin/(adminhtml|frontend)/(base|default)',
            'shell/'
        ];

    files.forEach(function (file) {
        coreFilesPatterns.some(function (pattern) {
             if (new RegExp(pattern, 'i').test(file)) {
                 console.log('Core file edited: ' + file);
                 exitCode = 1;

                 return true;
             }
        });
    });

    return exitCode;
}

module.exports.run = function () {
    var files = exec('git diff-index --name-only HEAD').toString().trim().split('\n');

    return module.exports.isCoreFileEdited(files);
}
