#!/usr/bin/env node

'use strict';

var exec = require('child_process').execSync;
var fs = require('fs');

module.exports.hasDebugCode = function (files) {
    var exitCode = 0,
        debugCodePatterns = [
            'var_dump',
            'Zend_Debug',
            'console\.log'
        ];

    files.forEach(function (file) {
        var data = fs.readFileSync(file).toString();

        debugCodePatterns.some(function (pattern) {
            var matches = data.match(new RegExp('.*' + pattern + '.*', 'gi'));
            (matches || []).forEach(function (match) {
               console.log('Debug call found: ' + match);
               exitCode = 1;
               return true;
            });
        });
    });

    return exitCode;
}

module.exports.run = function () {
    var files = exec('git diff-index --name-only HEAD').toString().trim().split('\n');

    return module.exports.hasDebugCode(files);
}
